config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :anomalys do
    resources :comments, only: [:create]
  end
  get "search_tag"=>"anomalys#search_tag"
  resources :comments, only: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :anomaly

  validates :comment_content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    @anomaly = Anomaly.find(params[:anomaly_id])
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "コメント投稿しました"
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = "コメントを入力してください"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
      @comment.destroy
      flash[:notice] = "コメント削除完了"
      redirect_to anomaly_path(@comment.anomaly_id)
  end
  
  private
  def comment_params
    params.require(:comment).permit(:comment_content, :anomaly_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="form-group col-md-10 offset-md-1">
  <div class="comment_form">
    <h6>コメント</h6>
    <%= form_with model:Comment.new, url: anomaly_comments_path(@anomaly.id), method: :post,local: true do |f| %>
      <div class="">
        <%= f.text_area :comment_content, class: "form-control-h form-control"%>
      </div>  
      <%= f.hidden_field :anomaly_id, value: @anomaly.id %>
      <%= f.submit '投稿', class: "post-comment offset-md-11" %>
    <% end %>
  </div>
</div>

app/views/comments/_list.html.erb
<div class="form-group col-md-10 offset-md-1">
  <% if @comments.any? %>
    <div class="comment_form ">
      <% @comments.each do |comment| %>
        <div class="comment_list">
          <%= link_to user_path comment.user do %>
            <i class="bi bi-person"></i>
            <span class="username"><%= comment.user.name %></span>
          <% end %>
        </div>
        <div class="">
          <%= comment.comment_content %>
        </div>
        <% if comment.user == current_user %>
          <div class="row">
            <div class="offset-md-11">
              <%= link_to comment_path(comment), method: :delete do %>
                <i class="bi bi-x"></i>削除
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="comment_none">コメントはありません。</div>
  <% end %>
</div>