config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :anomalys do
    resources :comments, only: [:create]
  end
  get "search_tag"=>"anomalys#search_tag"
  resources :comments, only: :destroy
end

app/models/anomaly.rb
class Anomaly < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  has_rich_text :content
  has_many :anomaly_tags,dependent: :destroy
  has_many :tags,through: :anomaly_tags
  belongs_to :user
  has_many :comments, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["title"]
  end

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_post_tag
    end
  end
end

app/controllers/anomalys_controller.rb
class AnomalysController < ApplicationController
  before_action :authenticate_user!, only: %i[new create update destroy edit]
  def index
    @q = Anomaly.ransack(params[:q])
    @anomalys = @q.result.includes(:tags, :anomaly_tags, :user).page(params[:page]).per(7)
    @tag_list=Tag.all
  end

  def new
    @user = current_user
    @anomaly = Anomaly.new
  end
  
  def create
    @anomaly = current_user.anomalys.new(anomaly_params)
    tag_list = params[:anomaly][:tag_name].split(',')
    if @anomaly.save
      @anomaly.save_tag(tag_list)
      flash[:notice] = "新規投稿をしました"
      redirect_to :anomalys
    else
      render "new"
    end
  end

  def show
    @anomaly = Anomaly.find(params[:id])
    @anomaly_tags = @anomaly.tags
    @comments = @anomaly.comments
  end

  def edit
    @user = current_user
    @anomaly = Anomaly.find(params[:id])
    @tag_list=@anomaly.tags.pluck(:tag_name).join(',')
  end

  def update
    @anomaly = Anomaly.find(params[:id])
    tag_list = params[:anomaly][:tag_name].split(',')
    if @anomaly.update(anomaly_params)
      # このanomaly_idに紐づいていたタグを@oldに入れる
      @old_relations=AnomalyTag.where(anomaly_id: @anomaly.id)
      # それらを取り出し消す。
      @old_relations.each do |relation|
      relation.delete
      end  
      @anomaly.save_tag(tag_list)
      redirect_to anomaly_path(@anomaly.id), notice: '更新完了しました'
    else
      render "edit"
    end
  end

  def destroy
    @anomaly = Anomaly.find(params[:id])
      @anomaly.destroy
      flash[:notice] = "削除しました"
      redirect_to anomalys_path
  end

  def search_tag
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @anomalys = @tag.anomalys.includes(:tags, :anomaly_tags, :user).page(params[:page]).per(7)
  end

  private
  def anomaly_params
    params.require(:anomaly).permit(:title, :content, :user_id)
  end
end

app/helpers/anomalys_helper.rb
module AnomalysHelper
end

app/views/anomalys/_anomaly_list.html.erb
<% @anomalys.each do |anomaly| %>  
  <div class="col-xs-12 anomalys">
    <div class="row">
      <div class="anomaly text-break m-mobile">
        <div class="anomaly-header">
        <i class="bi bi-person"></i>
          <%= link_to "#{anomaly.user.name}", users_path(anomaly.user.id), class:"erb-link" %>
          <%= "が投稿" %>
        </div>
        
        <div class="anomaly-content">
          <h4><%= link_to "#{anomaly.title}", anomaly_path(anomaly), class:"btn-block a-link" %></h4>
        </div>

        <% anomaly.tags.each do |tag| %>
          <i class="bi bi-tag"></i>
          <%= link_to tag.tag_name,search_tag_path(tag_id: tag.id)%>
        <% end %>
        
        <div class="text-right">
          <%= "作成日:#{anomaly.created_at.strftime('%Y/%m/%d %H:%M')}" %>
          <span class="mgr-10">
            <%= "更新日:#{anomaly.updated_at.strftime('%Y/%m/%d %H:%M')}" %>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/anomalys/_form.html.erb
<div class="form-group col-md-8 offset-md-2">
  <%= form_with model: @anomaly, url: anomalys_path do |f| %>
    <div class="new_form_frame">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, required: true, placeholder: "タイトル", class:"form-control form" %>
    </div>

    <div class="new_form_frame">
      <%= f.label :tag_name, "タグ" %>
      <%= f.text_field :tag_name, placeholder: "タグ (,で区切ると複数タグ登録できます)", class:"form-control form" %>
    </div>
  
    <div class='field new_form_frame'>
      <%= f.label :content, "本文" %>
      <%= f.rich_text_area :content %>
    </div>
  
    <div class="actions new_form_frame text-center">
      <%= f.submit "投稿", class:"post-btn mt-5 w-50" %>
    </div>
  <% end %>
</div>

app/views/anomalys/edit.html.erb
<h1 class="text-center">編集</h1>

<div class="form-group col-md-8 offset-md-2">
  <%= form_with model: @anomaly, url: anomaly_path do |f| %>
    <%= f.hidden_field :user_id, :value => @user.id %>
    <div class="new_form_frame">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, required: true, placeholder: "タイトル", class:"form-control form" %>
    </div>

    <div class="new_form_frame">
      <%= f.label :tag_name, "タグ" %>
      <%= f.text_field :tag_name, placeholder: "タグ (,で区切ると複数タグ登録できます)", class:"form-control form" %>
    </div>
  
    <div class='field new_form_frame'>
      <%= f.label :content, "本文" %>
      <%= f.rich_text_area :content %>
    </div>
  
    <div class="actions new_form_frame text-center">
      <%= f.submit "投稿", class:"post-btn mt-5 w-50" %>
    </div>
  <% end %>
</div>

app/views/anomalys/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12 text-center">
      <h2>異常一覧</h2>
    </div>
  </div>

  <% if user_signed_in? %>
    <div class="offset-md-10 post-form">
      <%= link_to '投稿する', new_anomaly_path, class:'btn btn-outline-post' %>
    </div>
  <% end %>

  <div class="search-form">
    <%= search_form_for @q, url: anomalys_path do |f| %>
      <div class="input-group">
        <%= f.search_field :title_cont, class: "form-control search-form-control col-md-5 offset-md-3 ", placeholder: 'キーワードを入力'  %>
          <span class="">
            <%= f.button type: :submit, class: "btn-search" do %>
              <i class="bi bi-search"></i>
            <% end %>
          </span>
      </div>
    <% end %>
  </div>

  <%= render 'anomaly_list' %>
  
  <%= paginate @anomalys %>
</div>

app/views/anomalys/new.html.erb
<h3 class="text-center">新規投稿</h3>
<%= render "shared/error", obj: @anomaly %>
<%= render "form" %>

app/views/anomalys/search_tag.html.erb
<div class="container-fluid">
<div class="anomaly-tags">
  <h3 class=" text-center"><%= "#{@tag.tag_name} を含む異常一覧" %></h3>
</div>
  <%= render 'anomaly_list' %>
</div>

app/views/anomalys/show.html.erb
<div class="container">
  <div class="anomaly-show text-break">
    <div class="row">
      <% if @anomaly.user == current_user %>
        <div class=" offset-md-10">
          <%= link_to edit_anomaly_path(@anomaly), class:"mgr-10" do %>
            <i class="bi bi-pencil"></i>編集
          <% end %>
          <%= link_to anomaly_path(@anomaly), method: :delete, data: { confirm: "削除しますか？" }, class:"mgr-10" do %>
            <i class="bi bi-x"></i>削除
          <% end %>
        </div>
      <% end %>
  
      <h2 class="my-3"><%= @anomaly.title %></h2>
    </div>
      <% @anomaly_tags.each do |tag| %>
        <i class="bi bi-tag"></i>
        <%= link_to tag.tag_name,search_tag_path(tag_id: tag.id)%><%="(#{tag.anomalys.count})" %>
      <% end %>
      <div class="anomaly_show_content">
        <%= @anomaly.content %>
      </div>
  </div>
  
  <%= render 'comments/list' %>

  <% if user_signed_in? %>
    <%= render "comments/form" %>
  <% end %> 
</div>