config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :anomalys do
    resources :comments, only: [:create]
  end
  get "search_tag"=>"anomalys#search_tag"
  resources :comments, only: :destroy
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>" role="alert">
    <a href="#" class="close text-white" data-dismiss="alert">×</a>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>Copyright ©︎ anocolle All Rights Reserved.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark p-2 header">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fas icon"></i>anocolle
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <%= link_to anomalys_path, class: "nav-link" do %>
              <i class="fas fa-user icon"></i>異常一覧
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to users_path(current_user), class: "nav-link" do %>
              <i class="fas fa-user icon"></i>マイページ
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
              <i class="fas fa-sign-out-alt icon"></i>ログアウト
            <% end %>
          <li>
        </ul>
      <% else %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <%= link_to new_user_registration_path, class: "nav-link" do %>
              <i class="fas fa-user-plus icon"></i>ユーザー登録
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to new_user_session_path, class: "nav-link" do %>
              <i class="fas fa-sign-in-alt icon"></i>ログイン
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class:'nav-link' %>
          </li>
        </ul>
      <% end %>  
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anocolle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>

    <%= yield %>

    <%= render "layouts/footer" %>
  </body>
</html>